dataloader:
  train_batch_size: 50
  valid_batch_size: 200
  num_workers: 8
  pin_memory: true
dataset:
  data_path: "data/broderick2019_eeg/Natural Speech/one_subject/"
  n_validation: 1024
model: "TDRL"
model_kwargs:
  x_dim: 128
  z_dim: 128
  lags: 2
  n_class: 1
  hidden_dim: 128
  embedding_dim: 2
  lr: 5.0e-4
  beta: 2.0e-3
  gamma: 2.0e-2
  correlation: 'Pearson'
  hmm_mode: 'mle_scaled:H'
trainer:
  accelerator: gpu
  default_root_dir: outputs/broderick2019_eeg/z128_c1_lags2_len2_Nlayer3/tdrl
  devices:
  - 0
  fast_dev_run: false
  max_epochs: 200
  val_check_interval: 0.1

