dataloader:
  train_batch_size: 64
  valid_batch_size: 256
  num_workers: 8
  pin_memory: true
dataset:
  data_path: "data/broderick2019_eeg/Natural Speech/train_data/subject1_bestruns20_stride8/lfreq10.0_hfreqNone_sfreq128.0_ch42_len10/"
  n_validation: 1024
model: "TDRL"
model_kwargs:
  x_dim: 42
  z_dim: 42
  lags: 2
  n_class: 1
  hidden_dim: 128
  embedding_dim: 2
  lr: 5.0e-4
  beta: 2.0e-3
  gamma: 2.0e-2
  correlation: 'Pearson'
  hmm_mode: 'mle_scaled:H'
trainer:
  accelerator: gpu
  default_root_dir: outputs/broderick2019_eeg/subject1_bestrun20_stride8_lfreq10.0_hfreqNone_sfreq128.0_ch42_len10/z128_c1_lags2_len8_Nlayer3/tdrl/
  devices:
  - 0
  fast_dev_run: false
  max_epochs: 200
  val_check_interval: 0.2

